export const shopData = [
  {
    id: 1,
    title: 'Stable Vices',
    author: 'Joanna Piotrowska',
    description: 'TThe themes of protection, freedom and oppression appear consistently throughout Polish artist Joanna Piotrowska’s oeuvre. Through three photographic series, Stable Vices focuses on these notions to crystallise a spectrum of concerns that drive her work.',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0035/7439/9040/products/cover484_1100x.jpg?v=1617716215',
    price: 40,
  },
    {
      id: 2,
      title: 'Andy Warhol Polaroids 1958-..',
      author: 'Reuel Golden',
      description: 'With a plethora of raw and unseen polaroids that give a glimpse into the life of the pop art maestro, this volume is Andy Warhol as we haven’t seen him before.',
      imageUrl: 'https://content.api.news/v3/images/bin/0d411870b28a11920b0407e274ab99e4?width=1024',
      price: 15,
    },
    {
      id: 3,
      title: 'David Shrigley: The Life Model',
      author: 'Max Delany',
      description: 'Compiling stories and articles from museum curators and literary luminaries, The Life Model looks closely at Shrigley’s Turner Prize-winning work.',
      imageUrl: 'https://content.api.news/v3/images/bin/0b8dee9e5ef3afb8dddf7aa72c237c08?width=1024',
      price: 28,
    },
    {
      id: 4,
      title: 'Bad New Days: Art, Criticism...',
      author: 'Hal Foster',
      description: 'Foster argues that the critic must still articulate a clear account of the contemporary in all its complexity. To that end, he offers several paradigms for the art of recent years, which he terms “abject,” “archival,” “mimetic,” and “precarious.”',
      imageUrl: 'https://i.pinimg.com/564x/48/3f/85/483f85375f660ceebbdd53b0a4978e7b.jpg',
      price: 28,
    },
    {
      id: 5,
      title: 'The Land in Between',
      author: 'Ursula Schulz-Dornburg',
      description: 'The Land in Between presents the complex bond between landscape and human civilization, exploring the construction of power though the built environment and its inevitable impermanence. ',
      imageUrl: 'https://cdn.shopify.com/s/files/1/0035/7439/9040/products/cover16_1100x.jpg?v=1573740816',
      price: 35,
    },
    {
      id: 6,
      title: 'Transparency is the new...',
      author: 'Mayumi Hosokura',
      description: ' Transparency is the new mystery comprises twenty-two images of nudes and crystals, by Japanese photographer Mayumi Hosokura. ',
      imageUrl: 'https://cdn.shopify.com/s/files/1/0035/7439/9040/products/cover59_1100x.jpg?v=1573740852',
      price: 28,
    },
    {
      id: 7,
      title: 'Women, Race & Class',
      author: 'Angela Y. Davis',
      description: 'Ranging from the age of slavery to contemporary injustices, this groundbreaking history of race, gender and class inequality by the radical political activist Angela Davis offers an alternative view of female struggles for liberation.',
      imageUrl: 'https://assets.thalia.media/img/artikel/29a645ce01b149421410743c5981ab34a5af7fa1-00-00.jpeg',
      price: 28,
    },
    {
      id: 8,
      title: 'Alice’s Adventures in..',
      author: 'Lewis Carroll & Yayoi Kusama',
      description: 'With this children’s book you can dive into the worlds of Alice in Wonderland and Yayoi Kusama at the same time and see that both are similar. It not only delights my five-year-old son, but also me',
      imageUrl: 'https://cdn.sanity.io/images/cxgd3urn/production/6465509ddead70c48bf002dad021a52fbd0f9757-1307x1600.jpg?w=1920&h=2350&fit=crop&auto=format',
      price: 28,
    },
    {
      id: 9,
      title: 'Women, Race & Class',
      author: 'Angela Y. Davis',
      description: 'Ranging from the age of slavery to contemporary injustices, this groundbreaking history of race, gender and class inequality by the radical political activist Angela Davis offers an alternative view of female struggles for liberation.',
      imageUrl: 'https://assets.thalia.media/img/artikel/29a645ce01b149421410743c5981ab34a5af7fa1-00-00.jpeg',
      price: 28,
    },
    {
      id: 10,
      title: 'Alice’s Adventures in..',
      author: 'Lewis Carroll & Yayoi Kusama',
      description: 'With this children’s book you can dive into the worlds of Alice in Wonderland and Yayoi Kusama at the same time and see that both are similar. It not only delights my five-year-old son, but also me',
      imageUrl: 'https://cdn.sanity.io/images/cxgd3urn/production/6465509ddead70c48bf002dad021a52fbd0f9757-1307x1600.jpg?w=1920&h=2350&fit=crop&auto=format',
      price: 28,
    },
  ];